//TODO: Change typeface over to what you have on Figma

//TODO: Swipeable delete for tasks

//TODO: Add native camera functionality

//TODO: Correctly link projects, tasks, and issues

//TODO: CREATE DIFFERENT KINDS OF USER ACCOUNTS

//TODO: ADD COMMENTS TO ISSUES AND PROJECTS

//TODO: SOCIAL NETWORK FUNCTIONS

//Heuristics Fixes

//TODO: ERROR MESSAGES FOR CREATE ACCOUNT/LOGIN/EDIT PROJECT NOT SPECIFIC ENOUGH. Revisit these error messages

//TODO: SEARCH/FILTER/SORT FUNCTIONALITY FOR PROJECTS/TASKS/ISSUES

//TODO: REVISIT ISSUE BUTTONS, REPLAE WITH LABELED ICONS AND CHANGE COLOUR FROM ORANGE TO GREY (KEEP DELETE RED)

//TODO: LOGIN/CREATE ACCOUNT BUTTONS SHOULD BE MORE VISIBLE AND IDENTIFIABLE AS BUTTONS

//TODO: CREATE ACCOUNT HEADER SHOULD HAVE A SPACE IN THE TITLE

//TODO: CHANGE DATE FORMAT

//TODO: CHANGE SUBMIT AND CANCEL BUTTON TO SOMETHING MORE INTUITIVE

//TODO: SEPARATE ISSUES AND TASKS TO OTHER SCREENS

//TODO: CLARIFY MEANING OF ISSUE DATES

//TODO: FILTER/DIFFERENTIATE BETWEEN RESOLVED AND UNRESOLVED ISSUES

//TODO: SEPARATE COMPLETED AND UNCCOMPLETED TASKS

//TODO: UPDATE USER ACCOUNT/DELETE ACCOUNT

//TODO: ADD CONFIRMATION DIALOGUE TO DELETES

//TODO: MAKE IT CLEAER HOW TO RETURN TO HOME SCREEN

//TODO: MAKE ISSUE LOG TITLES BIGGER

//TODO: MAKE SURE PADDING IS CONSISTENT THROUGHOUT SYSTEM ITEMS

//TODO: CHANGE 'CREATE NEW USER' TO 'CREATE ACCOUNT'

//TODO: MAKE IT CLEAR HOW MANY ISSUES AND TASKS ARE IN A PROJECT BEFORE CLICKING ON IT

//TODO: ADD USER MANUAL/HELP SECTION
